# Quantum Forge Activity 2
## This Notebook is for me to learn the basics of Jupyter notebooks and Python
I am excited to learn how to write Python code!

In [1]:
my_first_variable = "hello world"
print(my_first_variable)

hello world


In [2]:
import numpy as np

tau = 2*np.pi
print(tau)

6.283185307179586


In [4]:
string1 = "\u03C4 = {}".format(tau)
print(string1)
[0, 2, 3, 6, 2, 1]

τ = 6.283185307179586


In [7]:
tau_str = "\u03C4"
string2 = "{} = {}".format(tau_str, tau)
string3 = "{name} = {value}".format(name=tau_str, value=tau)
string4 = "{name} is a Greek letter pronounced 'tau' and it represents a full revolution around " \
"the circle; in radians {name} = {value}".format(name=tau_str, value=tau)
print(string2)
print(string3)
print(string4)

τ = 6.283185307179586
τ = 6.283185307179586
τ is a Greek letter pronounced 'tau' and it represents a full revolution around the circle; in radians τ = 6.283185307179586


In [8]:
print("{} = {:.2f}".format(tau_str, tau))

τ = 6.28


In [10]:
print(f"{tau_str} = {tau:.2f}")

τ = 6.28


In [11]:
my_first_list = ["this", "is", "my", "first", "list"]
print(my_first_list)

['this', 'is', 'my', 'first', 'list']


In [13]:
list_to_fill = [0] * 10
print(list_to_fill)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [15]:
list_to_fill[2] = 55
list_to_fill[7] = 12
print(list_to_fill)

[0, 0, 55, 0, 0, 0, 0, 12, 0, 0]


In [16]:
for ii in range(10):
    print(ii)
list_to_loop_over = 'the brown dog jumped over the white fence'.split(' ')
for list_element in list_to_loop_over:
    print(list_element)


0
1
2
3
4
5
6
7
8
9
the
brown
dog
jumped
over
the
white
fence


In [18]:
angles = [.03, 1.2, 0.25, 2.35, 0.044]
new_angles = [0] * len(angles)
for ii, angle in enumerate(angles):
    new_angles[ii] = angle + 2*np.pi*ii
    print(f'{ii}: {angle}')
print(new_angles)

0: 0.03
1: 1.2
2: 0.25
3: 2.35
4: 0.044
[0.03, 7.483185307179586, 12.816370614359172, 21.19955592153876, 25.176741228718345]


In [19]:
list1 = [1,2,3]
list2 = ['a', 'b', 'c']
for el1, el2 in zip(list1, list2):
    print(f'{el1} :: {el2}')

1 :: a
2 :: b
3 :: c


In [20]:
for el1 in list1:
    for el2 in list2:
        print(f'{el1} :: {el2}')

1 :: a
1 :: b
1 :: c
2 :: a
2 :: b
2 :: c
3 :: a
3 :: b
3 :: c


In [25]:
print(zip(list1,list2))
print(tuple(zip(list1,list2)))

((1, 'a'), (2, 'b'), (3, 'c'))


In [26]:
my_array = np.array([[1,2,3],[2,3,1]])
print(my_array.shape)

(2, 3)


In [27]:
x = np.arange(5)
y = np.array([[4],[2],[3],[1]])
print(x*x)
print(x*y)
print(y*y)
print(x+x)
print(x+y)
print(y+y)

[ 0  1  4  9 16]
[[ 0  4  8 12 16]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  1  2  3  4]]
[[16]
 [ 4]
 [ 9]
 [ 1]]
[0 2 4 6 8]
[[4 5 6 7 8]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [1 2 3 4 5]]
[[8]
 [4]
 [6]
 [2]]


In [1]:
x=np.array([1,3,4])
y=np.array([2,9,1])
sum(x*y)
print(x*y)
print(np.dot(x,y))

NameError: name 'np' is not defined

In [31]:
mat1 = np.array([[1,2],[1,2]])
mat2 = np.array([[2,1],[3,2]])
print(np.matmul(mat1,mat2))

[[8 5]
 [8 5]]
